title: Kamarul Ariffin Mansor
logo: https://scmathuitmkedah.github.io/ScMathUiTMKedah/images/profile2.png
description: |
  Senior Lecturer  Department of Mathematical Sciences  UiTM Kedah Branch Campus  ariff118@uitm.edu.my  +60 12 433 6901  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
