title: Kamarul Ariffin Mansor
logo: https://scmathuitmkedah.github.io/ScMathUiTMKedah/images/profile2.png
description: |
  Senior Lecturer \n
  Department of Mathematical Sciences \n
  UiTM Kedah Branch Campus \n
  ariff118@uitm.edu.my \n
  +60 12 433 6901  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
