title: Kamarul Ariffin Mansor
logo: https://scmathuitmkedah.github.io/ScMathUiTMKedah/images/profile2.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
